refined the makefile

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,72 +1,54 @@
 #!/bin/bash
 
-#take SVN version
-SVN_VERS=$(svnversion -n 2>/dev/null)
-if [ $? != 0 ]
+if [ -z "$1" ]
 then
-	SVN_VERS=undefined
+    if [ ! -f Makefile ]
+    then
+	#print help
+	echo "Error, use "$0" CC=(mpi c++ compiler) LEMON_PATH=(path to lemon installation) [CFLAGS=(additional flags)]"
+	exit 1
+    else
+	#read from Makefile
+	echo "Reading parameters from Makefile"
+	cc=$(awk -F := '$1=="CC"{print $2}' Makefile)
+	lemon_path=$(awk -F := '$1=="LEMON_PATH"{print $2}' Makefile)
+	cflags=$(awk -F := '$1=="CFLAGS"{print $2}' Makefile)
+    fi
+else
+    #parse arguments
+    until [ -z "$1" ]
+    do
+        if [ ${1:0:3} == "CC=" ];then cc=${1:3};fi                    #take mpi c++ compiler
+	if [ ${1:0:11} == "LEMON_PATH=" ];then lemon_path=${1:11};fi  #take lemon path
+	if [ ${1:0:7} == "CFLAGS=" ];then cflags=${1:7};fi            #take cflags
+	
+	shift #shift to next arguments
+    done
 fi
-
-#parse parameters
-until [ -z "$1" ]
-do
-  
-  #take mpi c++ compiler
-  if [ ${1:0:3} == "CC=" ]
-  then
-  	cc=${1:3}
-  fi
-
-  #take gnu compiler
-  if [ ${1:0:4} == "GCC=" ]
-  then
-  	gcc=${1:4}
-  fi
-
-  #take lemon path
-  if [ ${1:0:11} == "LEMON_PATH=" ]
-  then
-  	lemon_path=${1:11}
-  fi
-
-  #take cflags
-  if [ ${1:0:7} == "CFLAGS=" ]
-  then
-  	cflags=${1:7}
-  fi
-
-  shift
-done
 
 #check mpi c++ compiler set
 if [ "$cc" == "" ]
 then
-	echo "Error, set the mpi c++ compiler through: \"CC=\""
-	exit
-fi
-
-#check gnu compiler set
-if [ "$gcc" == "" ]
-then
-	echo "Error, set the gnu compiler through: \"GCC=\""
-	exit
+    echo "Error, set the mpi c++ compiler through: \"CC=\""
+    exit
 fi
 
 #check lemon path set
 if [ "$lemon_path" == "" ]
 then
-	echo "Error, set the path the lemon through: \"LEMON_PATH=\""
-	exit
+    echo "Error, set the path the lemon through: \"LEMON_PATH=\""
+    exit
 fi
-
+    
 
 #summarize
-echo "Using the following sets:"
+echo
+echo "Using the following parameters:"
+echo
 echo " CC=$cc"
-echo " GCC=$gcc"
 echo " LEMON_PATH=$lemon_path"
 echo " CFLAGS=$cflags"
-echo " SVN_VERS=$svn_vers"
+echo
 
 #preparing makefile
-sed "s/SED_GCC/$gcc/;s/SED_CC/$cc/;s|SED_LEMON_PATH|$lemon_path|;s/SED_CFLAGS/$cflags/" Makefile.default > Makefile
+sed "s|SED_CC|$cc|;s|SED_LEMON_PATH|$lemon_path|;s|SED_CFLAGS|$cflags|" default.Makefile > Makefile
